Add app-commit workflow and validations
- Introduced a new job for app-commit on develop branch.
- Added validation steps for API response including http_code, response_body, status field, error_message, and response_source.
- Updated README to reflect command changes and improved formatting.
- Enhanced input validation script to ensure file is provided for app-commit.

diff --git a/.github/workflows/pipeline-tests.yaml b/.github/workflows/pipeline-tests.yaml
--- a/.github/workflows/pipeline-tests.yaml
+++ b/.github/workflows/pipeline-tests.yaml
@@ -509,10 +509,82 @@ jobs:
           echo "[SUCCESS] All validations passed."
         shell: bash
 
+  app-commit-develop:
+    runs-on: ubuntu-latest
+    needs:
+      - upload-zip-with-commit-develop
+    environment:
+      name: ${{ contains(github.ref, 'develop') && 'development' || 'other' }}
+    if: github.ref == 'refs/heads/develop'
+    steps:
+      - uses: actions/checkout@v4.2.2
+      - name: AppCommit - Discloud API Action - ${{ vars.ENV_NAME }}
+        id: upload-zip
+        uses: marco-quicula/discloud-api-action@develop
+        with:
+          discloud_api_token: ${{ secrets.DISCLOUD_API_TOKEN }}
+          command: 'app-commit'
+          file: '${{ vars.JAVA_APP_ZIP_FILE }}'
+
+      - name: AppCommit - Validate Outputs
+        run: |
+          errors=0
+
+          # Validate http_code
+          if [ "${{ steps.upload-zip.outputs.http_code }}" -ne 200 ]; then
+            echo "[ERROR] http_code is not 200. http_code=${{ steps.upload-zip.outputs.http_code }}"
+            errors=$((errors+1))
+          else
+            echo "[SUCCESS] http_code is valid. http_code=${{ steps.upload-zip.outputs.http_code }}"
+          fi
+
+          # Validate response_body
+          response_body=$(echo "${{ steps.upload-zip.outputs.response_body }}" | base64 --decode)
+          if [ -z "$response_body" ]; then
+            echo "[ERROR] response_body is empty."
+            errors=$((errors+1))
+          else
+            echo "[SUCCESS] response_body is not empty."
+
+            # Validate "status" field in response_body
+            status=$(echo "$response_body" | jq -r ".status")
+            if [ "$status" != "ok" ]; then
+              echo "[ERROR] 'status' in response_body is not 'ok'. Actual status: $status"
+              errors=$((errors+1))
+            else
+              echo "[SUCCESS] 'status' in response_body is 'ok'."
+            fi
+          fi
+
+          # Validate error_message
+          if [ -n "${{ steps.upload-zip.outputs.error_message }}" ]; then
+            echo "[ERROR] error_message is not empty."
+            errors=$((errors+1))
+          else
+            echo "[SUCCESS] error_message is empty."
+          fi
+
+          # Validate response_source
+          if [ "${{ steps.upload-zip.outputs.response_source }}" != "api" ]; then
+            echo "[ERROR] response_source is not 'api'. response_source=${{ steps.upload-zip.outputs.response_source }}"
+            errors=$((errors+1))
+          else
+            echo "[SUCCESS] response_source is 'api'. "
+          fi
+
+          # Exit with error if any validation failed
+          if [ $errors -ne 0 ]; then
+            echo "[FAILURE] Validation failed with $errors error(s)."
+            exit 1
+          fi
+
+          echo "[SUCCESS] All validations passed."
+        shell: bash
+
   app-status-200-develop:
     runs-on: ubuntu-latest
     needs:
-    - upload-zip-with-commit-develop
+    - app-commit-develop
     environment:
       name: ${{ contains(github.ref, 'develop') && 'development' || 'other' }}
     if: github.ref == 'refs/heads/develop'
